### ISSUE TITLE
version installed doesn't match the examples/docs

### ISSUE THREAD

**Issue by samlaf** [blockworks-foundation/mango-client-v3#112]
`npm install @blockworks-foundation/mango-client` and `yarn add @blockworks-foundation/mango-client` both download version 2.2.1, whose directory structure only has `lib/` and no `src/`, whereas all the examples and docs (eg. https://docs.mango.markets/developer-resources/code-examples#subscribe-to-an-order-book) import from `src`.

I had to manually specify the recent version: `yarn add @blockworks-foundation/mango-client@3.6.10`.
I think the npm package should be updated.

**Comment by riordanp** [comment]
Thanks for reporting, have changed the latest tag to 3.6.10.
